# Generated by Django 2.2 on 2021-12-30 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('status', models.BooleanField(default=True, verbose_name='وظعیت')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='blog.CategoryModel', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندیها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='محتوا')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='عکس')),
                ('create', models.DateTimeField(verbose_name='زمان ساخت')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ساخت')),
                ('update', models.DateTimeField(verbose_name='بروزرسانی در')),
                ('status', models.CharField(choices=[('publish', 'منتشر شد'), ('draft', 'پیش نویس')], max_length=15, verbose_name='وظعیت')),
                ('auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='childrens', to='blog.CategoryModel', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['publish'],
            },
        ),
    ]
