# Generated by Django 2.2 on 2022-01-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220102_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='create',
            field=models.DateTimeField(verbose_name='زمان ساخت'),
        ),
    ]
