# Generated by Django 2.2 on 2022-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220102_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='create',
            field=models.DateTimeField(default=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='update',
            field=models.DateTimeField(default=True, verbose_name='بروزرسانی در'),
        ),
    ]
