# Generated by Django 2.2 on 2022-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220102_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='create',
            field=models.DateTimeField(verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='update',
            field=models.DateTimeField(verbose_name='بروزرسانی در'),
        ),
    ]
