# Generated by Django 2.2 on 2022-01-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220102_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='status',
            field=models.CharField(choices=[('publish', 'منتشر شد'), ('draft', 'پیش نویس'), ('investigation', 'درحال بررسی'), ('back', 'برگشت داده شده')], max_length=15, verbose_name='وظعیت'),
        ),
    ]
