# Generated by Django 2.2 on 2022-01-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220105_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
    ]
